[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.95"

[dependencies.web-sys]
version = "0.3.72"
features = ["Window", "console", "Document", "Element", "HtmlCanvasElement", "CanvasRenderingContext2d", "Performance"]
